In [2]:
import numpy as np    
import pandas as pd

In [22]:
#  Load Data

df = pd.read_csv(r'E:\Test trail\Data\train_set.csv')
X = df.iloc[:, :-1].values
y = df.iloc[:,1:].values

In [23]:
df.head()

,Year,OGC,OG,DC,Dept,UC,Union,JF,Job,EI,Salaries,Overtime,H/D,YT,Total_Compensation
0,2015,4,Community Health,DPH,Public Health,250,"SEIU - Health Workers, Local 1021",Med Therapy & Auxiliary,Morgue Attendant,6725,12196,0,0.00,Calendar,16158
1,2013,4,Community Health,DPH,Public Health,39,"Stationary Engineers, Local 39",Journeyman Trade,Stationary Engineer,25058,74639,2820,12703.31,Fiscal,115784
2,2015,6,General Administration & Finance,ASR,Assessor/Recorder,21,"Prof & Tech Engineers - Miscellaneous, Local 21",Appraisal & Taxation,Senior Real Property Appraiser,46108,100554,0,12424.50,Calendar,144708
3,2016,1,Public Protection,POL,Police,911,Police Officers' Association,Police Services,Sergeant 3,33369,140164,52754,13043.87,Fiscal,242323
4,2013,2,"Public Works, Transportation & Commerce",HHP,PUC Hetch Hetchy,21,"Prof & Tech Engineers - Miscellaneous, Local 21",Information Systems,IS Engineer-Journey,28684,58813,0,7655.28,Calendar,82106

In [24]:
df = df.drop(['OG','Dept','Union','Job','H/D','YT'], axis=1)
df.head()

,Year,OGC,DC,UC,JF,EI,Salaries,Overtime,Total_Compensation
0,2015,4,DPH,250,Med Therapy & Auxiliary,6725,12196,0,16158
1,2013,4,DPH,39,Journeyman Trade,25058,74639,2820,115784
2,2015,6,ASR,21,Appraisal & Taxation,46108,100554,0,144708
3,2016,1,POL,911,Police Services,33369,140164,52754,242323
4,2013,2,HHP,21,Information Systems,28684,58813,0,82106